name: Tests

# Controls when the action will run.
on:
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build-and-test"
  test:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Test 🔧
        run: |
          npm install
          npm test